In [1]:
#List vs Numpy:
#Lists are slow and NUmpy are quick to run
##Lists store multiple data type value as compared to numpy that only stores data as Int.
###so when running a list, a computer does check every dtype of list before loading it to memory hence taking more time.

#Lists when stored in a memory is randomly and spacially loacted. whereas numpy stores data contiguously saving space and indexes
## We need to 

In [3]:
import numpy as np

In [10]:
# to know the dimension of your numpy array:
a = np.array([1,2,3])
b= np.array([[1,2],[3,4],[5,6]])
print(a)

[1 2 3]


In [8]:
a.ndim

1

In [11]:
b.ndim

2

In [12]:
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
b.shape

(3, 2)

In [17]:
b.dtype

dtype('int32')

In [18]:
#to know the size of 'a' in bytes
a.itemsize

4

In [19]:
#to know the memory 'a' takes :
a.nbytes

12

In [23]:
a= np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
a[:, -2]

array([ 6, 13])

In [26]:
#[startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [27]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [28]:
a[:, 5] = 0
print(a)

[[ 1  2  3  4  5  0  7]
 [ 8  9 10 11 12  0 14]]


In [29]:
a[1,:]=0
print(a)

[[1 2 3 4 5 0 7]
 [0 0 0 0 0 0 0]]


In [30]:
# 3 dimension example
b= np.array([[[1,2],[1,3]],[[4,5],[6,4]]])
print(b)

[[[1 2]
  [1 3]]

 [[4 5]
  [6 4]]]


In [ ]:
#get specific element: work outside in
